import Head from 'next/head'
import Image from 'next/image'

import Banner from '../components/banner'
import Card from '../components/card'

import coffeeStores from '../data/coffee-stores.json';
import { fetchCoffeeStores } from '../lib/coffee-stores';

import styles from '../styles/Home.module.css'

export default function Home(props) {
  const handleOnBannerBtnClick = () => {

  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="View stores nerby" handleOnClick={handleOnBannerBtnClick} />
        <div className={styles.heroImage}>
          <Image src="/hero-image.png" width={700} height={400} />
        </div>
        {props.coffeeStores.length > 0 && <>
          <h2 className={styles.heading2}>Toronto stores</h2>
          <div className={styles.cardLayout}>
            {props.coffeeStores.map(store => <Card key={store.id} className={styles.card} name={store.name} href={`/coffee-store/${store.id}`} imgUrl={store.imgUrl || "https://images.unsplash.com/photo-1498804103079-a6351b050096?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2468&q=80"} />)}
          </div>
        </>}
      </main>
    </div>
  )
}

export async function getStaticProps(context) {
  
  const coffeeStores = await fetchCoffeeStores();

  return {
    props: {
      coffeeStores
    },
  }
}